apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: dp-rapid-meldingskatalog
  namespace: teamdagpenger
  labels:
    team: teamdagpenger
spec:
  image: {{ image }}
  port: 8080
  prometheus:
    enabled: true
    path: /metrics
  liveness:
    path: /isalive
  readiness:
    path: /isready
  startup:
    path: /isready
  replicas:
    min: 1
    max: 1
  resources:
    limits:
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi
  {{ ingresses }}
  secureLogs:
    enabled: true
  env:
    - name: KAFKA_RAPID_TOPIC
      value: teamdagpenger.rapid.v1
    - name: KAFKA_CONSUMER_GROUP_ID
      value: dp-rapid-meldingskatalog-v3
    - name: KAFKA_RESET_POLICY
      value: earliest
    - name: FLYWAY_CLEAN_DISABLED
      value: "false"
    - name: CLEAN_ON_STARTUP
      value: "false"
  kafka:
    pool: {{ kafka_pool }}
  azure:
    application:
      enabled: true
      tenant: nav.no
      claims:
        groups:
          - id: 4edb2ce5-4f0e-4f6f-9b82-b8e75e9dd09e # teamdagpenger
  accessPolicy:
    inbound:
      rules:
        - application: dp-aktivitetslogg-frontend
        {{#if wonderwalled}}
        - application: wonderwalled-azure
          namespace: aura
       {{/if}}