/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/melding": {
    /** Gir en liste over alle meldinger som har vært publisert på rapiden */
    get: operations["get-meldinger"];
  };
  "/melding/{meldingsreferanseId}/innhold": {
    /** Gir innholdet i en bestemt melding */
    get: operations["get-melding-innhold"];
    parameters: {
      path: {
        meldingsreferanseId: string;
      };
    };
  };
  "/meldingstype": {
    /** Gir en liste med alle kjente meldingstyper */
    get: operations["get-meldingstyper"];
  };
  "/meldingstype/{meldingstype}": {
    /** Gir en bestemt meldingstype */
    get: operations["get-meldingstype"];
    parameters: {
      path: {
        meldingstype: components["parameters"]["Meldingstype"];
      };
    };
  };
  "/meldingstype/{meldingstype}/meldinger": {
    /** Gir en liste med meldinger av en bestemt meldingstype */
    get: operations["get-meldinger-per-meldingstype"];
    parameters: {
      path: {
        meldingstype: components["parameters"]["Meldingstype"];
      };
    };
  };
  "/meldingstype/{meldingstype}/schema": {
    /** Gir et JSON Schema som brukes for å validere meldinger av en bestemt meldingstype */
    get: operations["get-melding-schema"];
    parameters: {
      path: {
        meldingstype: components["parameters"]["Meldingstype"];
      };
    };
  };
  "/meldingstype/{meldingstype}/mock": {
    /** Gir en generert melding av en bestemt meldingstype */
    get: operations["get-melding-mock"];
    parameters: {
      path: {
        meldingstype: components["parameters"]["Meldingstype"];
      };
    };
  };
  "/system": {
    /** Gir en liste om alle system og hvilke meldinger de produserer */
    get: operations["get-system"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    System: {
      navn?: string;
      meldinger?: components["schemas"]["Meldingstype"][];
    };
    /** @description Meldingstype */
    Meldingstype: {
      /** @example Journalpost */
      navn?: string;
      /** @example Behov */
      type?: string;
      antall?: number;
      systemer?: components["schemas"]["System"][];
    };
    /** @description Melding */
    Melding: components["schemas"]["MeldingKonvolutt"] & {
      type?: components["schemas"]["MeldingType"];
    };
    /**
     * @description Hva slags melding det er
     * @enum {string}
     */
    MeldingType: "Hendelse" | "Behov" | "Løsning";
    /** @description Konvolutt som er felles for alle meldinger */
    MeldingKonvolutt: {
      /** Format: uuid */
      meldingsreferanseId: string;
      /** Format: date-time */
      opprettet: string;
      eventName: string;
      sporing: components["schemas"]["MeldingSporing"][];
    };
    /** @description Sporing av melding */
    MeldingSporing: {
      /** Format: uuid */
      id: string;
      /** Format: date-time */
      time: string;
      service?: string;
      instance?: string;
      image?: string;
    };
  };
  responses: never;
  parameters: {
    Meldingstype: string;
  };
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {

  /** Gir en liste over alle meldinger som har vært publisert på rapiden */
  "get-meldinger": {
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["Melding"][];
        };
      };
    };
  };
  /** Gir innholdet i en bestemt melding */
  "get-melding-innhold": {
    parameters: {
      path: {
        meldingsreferanseId: string;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": unknown;
        };
      };
    };
  };
  /** Gir en liste med alle kjente meldingstyper */
  "get-meldingstyper": {
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["Meldingstype"][];
        };
      };
    };
  };
  /** Gir en bestemt meldingstype */
  "get-meldingstype": {
    parameters: {
      path: {
        meldingstype: components["parameters"]["Meldingstype"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["Meldingstype"];
        };
      };
    };
  };
  /** Gir en liste med meldinger av en bestemt meldingstype */
  "get-meldinger-per-meldingstype": {
    parameters: {
      path: {
        meldingstype: components["parameters"]["Meldingstype"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["Melding"][];
        };
      };
    };
  };
  /** Gir et JSON Schema som brukes for å validere meldinger av en bestemt meldingstype */
  "get-melding-schema": {
    parameters: {
      path: {
        meldingstype: components["parameters"]["Meldingstype"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["Melding"][];
        };
      };
    };
  };
  /** Gir en generert melding av en bestemt meldingstype */
  "get-melding-mock": {
    parameters: {
      path: {
        meldingstype: components["parameters"]["Meldingstype"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["Melding"][];
        };
      };
    };
  };
  /** Gir en liste om alle system og hvilke meldinger de produserer */
  "get-system": {
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["System"][];
        };
      };
    };
  };
}
